# Generated by Django 3.0.5 on 2020-06-01 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='health_officer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='health_officer_diagnoses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='status',
            field=models.CharField(choices=[('WA', 'WAITING'), ('PR', 'PROCESSING'), ('AR', 'AWAITING_REVIEW'), ('RE', 'REVIEWED')], default='WA', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_diagnoses', to=settings.AUTH_USER_MODEL),
        ),
    ]
