# Generated by Django 3.0.5 on 2020-06-01 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200601_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='status',
            field=models.CharField(choices=[('ND', 'NEEDS_DATA'), ('WA', 'WAITING'), ('PR', 'PROCESSING'), ('AR', 'AWAITING_REVIEW'), ('RE', 'REVIEWED')], max_length=2),
        ),
        migrations.CreateModel(
            name='DiagnosisResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField()),
                ('confidence', models.FloatField()),
                ('has_covid', models.BooleanField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Diagnosis')),
            ],
        ),
    ]
